# Generated by Django 4.2.6 on 2023-11-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doctor_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Reclamo'], [1, 'Sugerencia'], [2, 'Toma de Hora'], [3, 'Otros']])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
