# Generated by Django 4.2.6 on 2023-11-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_contacto_tipo_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'otros']], default=1),
            preserve_default=False,
        ),
    ]
