# Generated by Django 4.2.6 on 2023-11-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contacto_tipo_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='fechas',
        ),
        migrations.AddField(
            model_name='doctor',
            name='fechas',
            field=models.ManyToManyField(to='app.fechaconsulta'),
        ),
    ]
