# Generated by Django 4.0.1 on 2023-11-21 21:30

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_agendadoctor_remove_doctor_fechas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendadoctor',
            name='dia',
            field=models.DateField(help_text='Introduzca una fecha para el calendario', validators=[app.models.validar_dia]),
        ),
        migrations.AlterField(
            model_name='agendadoctor',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='app.doctor'),
        ),
        migrations.AlterField(
            model_name='agendadoctor',
            name='horario',
            field=models.CharField(choices=[('1', '07:00 a 08:00'), ('2', '08:00 a 09:00'), ('3', '09:00 a 10:00'), ('4', '10:00 a 11:00'), ('5', '11:00 a 12:00')], max_length=10),
        ),
        migrations.AlterField(
            model_name='agendadoctor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
