# Generated by Django 4.0.1 on 2023-11-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_agendadoctor_dia_alter_agendadoctor_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendadoctor',
            name='rut',
            field=models.CharField(default=0, help_text='Ingrese su rut', max_length=12),
            preserve_default=False,
        ),
    ]
